---

services:
  - type: web
    name: ab-directus-server
    plan: starter
    region: frankfurt
    runtime: image
    image:
      url: docker.io/directus/directus:10
    envVars:
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET
        generateValue: true
      - key: DB_CLIENT
        value: pg
      - key: DB_CONNECTION_STRING
        fromDatabase:
          name: ab-directus-db
          property: connectionString

databases:
  - name: ab-directus-db
    plan: starter
    region: frankfurt
    ipAllowList: [] # No public access