---
services:
  - type: web
    name: ab-directus-server
    plan: starter
    region: frankfurt
    runtime: docker
    image:
      url: docker.io/directus/directus:latest
    envVars:
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SECRET
        generateValue: true
      - key: DB_CLIENT
        value: postgres
      - key: DB_DATABASE
        fromDatabase:
          name: ab-directus-db
          property: database
      - key: DB_HOST
        fromDatabase:
          name: ab-directus-db
          property: host
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        fromDatabase:
          name: ab-directus-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ab-directus-db
          property: password

databases:
  - name: ab-directus-db
    plan: starter
    region: frankfurt
    ipAllowList: [] # No public access
    databaseName: directus
